# About this file
#
# TIOF Tags reference: http://TIOF.Click/Tags

- name: "type: blocker"
  color: "3498DB"
  description: "A blocker for the release."
  
# Channels
  
- name: "type: blocker CHANNEL"
  color: "3498DB"
  description: "A blocker for the release CHANNELED."

"- name: ""⌨ Need: Code""
  color: ""#1d76db""
  description: ""This Issue involves some sort of coding.
"""


"- name: ""⌨ Need: Code""
  color: ""#1d76db""
  description: ""This Issue involves some sort of coding.
"""
